### ISSUE TITLE
Allow selection of version

### ISSUE THREAD

**Issue by richfitz** [mrc-ide/didehpc#20]

**Comment by jackolney** [comment]
Yes please. I have a package that depends on >=3.3.0

I have just changed the `R_VERSION` variable in my fork and that seems to work: https://github.com/jackolney/didewin/commit/bd2fa0aecc14326ed2222eb8279f225d31c38f3d

**Comment by jackolney** [comment]
Okay, it appears my fix breaks `context::cross_install_packages()` :disappointed:

**Comment by richfitz** [comment]
This was exactly what I was working on before the break but I did not get it working in time. I'm currently in NZ and back on the 13th and can work with you to try the new version asap.

The new version fixes this properly (you can select any version) but it required rewriting most of the gnarly cross installation code.

**Comment by richfitz** [comment]
A possible hack though. Many packages that "require" recent R actually don't. Devtools adds these version requirements aggressively and without checking that they're needed. If you use a local copy with the version requirements downgraded it will often work fine.

Done packages do of course require their stated version
