### ISSUE TITLE
Tracking failed jobs

### ISSUE THREAD

**Issue by jameshay218** [mrc-ide/didehpc#22]
When submitting jobs through the didewin package, jobs that return status `ERROR` do not enter the failed state on the HPC web portal.

**Comment by richfitz** [comment]
I think this is because I am no longer correctly setting `CONTEXT_PROPAGATE_ERROR = TRUE` in the batch file environment variables

**Comment by richfitz** [comment]
hmm, actually it there.  But that's the thing that should be controlling whether we end up throwing...
