### ISSUE TITLE
errors don't show in the HPC software

### ISSUE THREAD

**Issue by tinigarske** [mrc-ide/didehpc#3]
When I'm running jobs on nodes with not enough memory and they fail, I get the normal R error message in the log script, but in the HPC software the job is logged as finished, which is a little inconvenient. It does come up as ERROR in the task bundle object. However, if I run really long jobs I don't really want to keep the R session running until the jobs are finished (I might even switch off my computer over night). Can I even get the ids back if I've exited the R session? Or would it be worthwhile to output the task bundle object as an .RData file so I can get back to it?

**Comment by richfitz** [comment]
You can close your R session for sure, and close your computer.  Everything is safe in the `contexts` directory.  Getting the ids back will at the moment involve perhaps a little faff but it's all there and we can add interfaces to make it simpler.

I can set the task runner to throw on exit if the job fails -- that's a really good idea.

**Comment by tinigarske** [comment]
Great, thanks!

**Comment by richfitz** [comment]
This is awkward to put into `context:R/main.R::main()` because that will affect all uses.  We could do it with an environment variable that is read there probably, but possibly it should be another option...

**Comment by richfitz** [comment]
This appears to be a problem again
