### ISSUE TITLE
aborting jobs

### ISSUE THREAD

**Issue by tinigarske** [mrc-ide/didehpc#7]
Is it possible to cancel jobs that I've submitted? Is it possible to do this in batch?

**Comment by richfitz** [comment]
Good question.  I think I implemented this somewhere and will try and dig it out.  I hope to get onto documentation soonish so will make sure to add this.

**Comment by richfitz** [comment]
For my record as much as anything else, the method of the queue to cancel jobs is `unsubmit()` which is takes a vector of job ids as input.

**Comment by richfitz** [comment]
Fixed in update, where it is tested
